### ISSUE TITLE
Error uploading CSS files

### ISSUE THREAD

**Issue by PatrikM99** [MscrmTools/MscrmTools.PortalCodeEditor#18]
When updating css files via the tool, it gets igonored by the browser.
If I update them manualy in crm it works fine.

The problem is that the tool assigns incorrect content-type to uploaded resources.

For example, .ccs files get "octet-stream" instead of correct value. So browser treats them as binary files, not a style files and they got ignored.

**Comment by MscrmTools** [comment]
Thank you for the feedback.
I will work on it

**Comment by PFD057** [comment]
Hi all

We have the same problem since the CRM portal version 9.1.9.67 of September 21, 2019.
In fact, we have also webfiles that contain CSS and JS files for a custom portal and sometimes these web pages that contain css/js web have the same error : 

"resource interpreted as stylesheet but transferred with mime type application/octet-stream"

Note: In portal version 9.1.8.21, loading CSS and JS sources is not a problem and applies correctly to loading web pages.

We also noticed that the css/js files are in UTF8 format when they are attached in a CRM note or by admin interface in front website.

In a few weeks the Portal CRM production versions will be impacted by this bug...
Thanks by advance for your help ;)
Kind regards

**Comment by MscrmTools** [comment]
Fixed in latest version
